apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jdqm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-jdqm@sha256:033be0c750e734d0ed1fa88f7aa9dc25b4c1b225c70e6ab949a4f8b63371ebb6
        name: my-nodejs
        resources: {}
status: {}
